channels:
- CK5
- CK7
- CK8-18
- CK14
- CK19
- HER2
- EGFR
- CD31
- vWF
- SMA
- Vimentin
- Fibronectin
- CD45
- CD3
- CD20
- CD68
- CD44
- p53
- Ki67
- PanCK
- B-catenin
- SOX9
- S6
- Twist
- GATA3
- Slug
- c-Caspase-3
- EP2
- SP2
- CA9
- c-PARP
- CD163
- MECA-79
- CD4
- SOX10
- CD103
- TCF1
- GZMB
- CD56
- Bax
- CD14
- IDO
- FoxP3
- CD8
- COL1
- HLA-Class-2
- TIM3
- PD1
- LAG3
- CD11c
- CD69
- HLA-Class-1
- CD45RA
- DC-SIGN
- CD21
- CD274
- MelanA
- Calprotectin
- Tox-Tox2
- CD45RO
- CD206
- CCR7
- pS6
- CK17
- PDL1
- CD138
- CD16
- CD209
- CK6
- CD63
- MPO
- OX40
- CD11b
- B-tubulin
- PAX5
- HIF1A
- COX2
- ER
- IDO1
- P63
- MMP9
- AR
- Tryptase
- E-cadherin
- FAP
- GLUT1
- CD36
- HK1
- PKM2
- LDHA
- CPT1A
- XBP1
- ATP5A
- SDHA
- CD57
- CD98
- Na-K-ATPase
- IDH
- ASCT2
- CD39
- G6PD
- NRF2
- CS
- VDAC1
- Intelectin-1
- CD66
- MUC2
- Syndecan-1
- CDX2
- NKG2D
- c-kit
- CD19
- Col4
- DEFAL5
- Synaptophysin
- Bcl-2
- CD34
- CD49f
- CgA
- CD90
- CD123
- CD15
- CD49a
- CD7
- OLFM4
- MUC1
- CD38
- CD127
- CD25
- PDPN
- MUC6
- KLRB1
- IgA
- Lysozyme
- IFNg
- iNOS
- Trypase
- gdTCR
- CD94
- CD8a
- TTF1
- P2Y12
- PMEL
- SOX2
- OLIG2
- GFAP
- MCT1
- gH2AX
- IL6
- Amylase
- CXCL5
- GATA6
- MMP7
- FASN
- CD80
- HO1
- Galectin9
- HLA-G
- TIGIT
- ICOS
- Lck
