channels:
- CALPROTECTIN
- CD103
- CD11B
- CD11C
- CD127
- CD134
- CD14
- CD16
- CD161
- CD163
- CD19
- CD20
- CD206
- CD209
- CD25
- CD276
- CD278/ICOS
- CD3
- CD31
- CD38
- CD4
- CD44
- CD45
- CD45RA
- CD45RO
- CD49a
- CD56
- CD63
- CD68
- CD69
- CD7
- CD8
- CD80
- CSF1R
- ECADHERIN
- EGFR
- FAP
- FOXP3
- GALECTIN9
- HER2
- HLAII
- LAG3/CD223
- LCK
- MPO
- NKG2D
- PANCK
- PD1
- PDL1
- TRYPTASE
- VIMENTIN
cell_types:
- BACKGROUND
- BCELL
- DENDRITIC
- ENDOTHELIAL
- EPITHELIAL
- FIBROBLAST
- MACROPHAGE
- MAST
- MONOCYTE
- NEUTROPHIL
- NK
- TCELL/TREG
- TUMOR
