Cell: '#000000'
Immune: '#fabebe'
Lymphocyte: '#fc5603'
Tcell: '#fc7d05'
Treg: '#fca451'
CD4T: '#d46904'
CD8T: '#b55902'
NKT: '#a65102'
Bcell: '#fc5947'
Plasma: '#fa8e82'
NK: '#ffb303'
Myeloid: '#ff030f'
Dendritic: '#fc4c55'
Granulocyte: '#fc7279'
Mast: '#c2555b'
Neutrophil: '#a82027'
Macrophage: '#f20045'
M1Macrophage: '#f73e88'
M2Macrophage: '#f27cab'
Monocyte: '#d40492'
Epithelial: '#f7fcb6'
Myoepithelial: '#878658'
Secretory: '#e4fc0a'
Goblet: '#c6db09'
Paneth: '#cccc2b'
Acinar: '#e7fc26'
Enterocyte: '#99f002'
ICC: '#5ec206'
Endothelial: '#03fcec'
LymphaticEndothelial: '#00e3b9'
BloodVesselEndothelial: '#02b884'
Stromal: '#02fae9'
Fibroblast: '#02b0aa'
Myofibroblast: '#017571'
Muscle: '#08daff'
SmoothMuscle: '#0483ba'
Endocrine: '#1303fc'
Neuroendocrine: '#4d77f7'
Nerve: '#9d03fc'
Glia: '#8265a1'
Astrocyte: '#610394'
Neuron: '#c838fc'
Tumor: '#7d7134'
EVT: '#6b4862'
Background: '#FFFFFF'
Unknown: '#000000'
TransitAmplifying: '#57919c'
GiantCell: '#49496b'


