Cell:
      Immune:
            Lymphocyte:
                  Tcell:
                        Treg: {}
                        CD4T: {}
                        CD8T: {}
                        NKT: {}
                  Bcell:
                        Plasma: {}
                  NK: {}
            Myeloid:
                  Dendritic: {}
                  Granulocyte:
                        Mast: {}
                        Neutrophil: {}
                  Macrophage:
                        M1Macrophage: {}
                        M2Macrophage: {}
                  Monocyte: {}
      Epithelial:
            Myoepithelial: {}
            Secretory:
                  Goblet: {}
                  Paneth: {}
                  Acinar: {}
            Enterocyte: {}
            ICC: {} # Interstitial Cell of Cajal, Mesenchymal or Epithelial, both are possible
      Endothelial:
            LymphaticEndothelial: {}
            BloodVesselEndothelial: {}
      Stromal:
            Fibroblast:
                  Myofibroblast: {}
            Muscle:
                  SmoothMuscle: {}
      Endocrine:
            Neuroendocrine: {}
      Nerve:
            Glia:
                  Astrocyte: {}
            Neuron: {}
      Tumor: {}
      EVT: {}
      Background: {}
      Unknown: {}
      TransitAmplifying: {}
      GiantCell: {}
# TODO: add cell state mapping later
# APC: Antigen Presenting Cell, including dendritic cells, macrophages, and B cells, Langerhans
# Leukocyte: Neutrophils, Lymphocytes, Eosinophils, Basophils, Monocytes
# Megakaryocyte: A cell found in the bone marrow. This can include fibroblasts, macrophages, adipocytes, osteoblasts, osteoclasts, endothelial cells and hematopoietic cells.
# Kupffer Cells: In liver, macrohpages are called Kupffer Cells
# CellDeath: Necrotic, Apoptotic (Apototic is tumor, according to the paper, so ignore this part for now)
