Tissue-Breast/Liu_Validation_MIBI: MIBI
Tissue-Breast/Keren_TNBC_MIBI: MIBI
Tissue-Breast/Risom_DCIS_MIBI: MIBI
Tissue-Breast/Jackson_BreastCancer_IMC: IMC
Tissue-Breast/Keren_New_MIBI: MIBI
Tissue-Breast/Danenberg_BreastCancer_IMC: IMC
Tissue-GI/Liu_Validation_MIBI: MIBI
Tissue-GI/Keren_GVHD_MIBI: MIBI
Tissue-GI/Hartmann_CRC_MIBI: MIBI
Tissue-GI/Hickey_Colon_CODEX: CODEX
Tissue-Immune/Liu_Validation_MIBI: MIBI
Tissue-Lung/Sorin_Lung_IMC: IMC
Tissue-Lung/McCaffrey_TB_MIBI: MIBI
Tissue-Lymph_Node/Liu_Validation_MIBI: MIBI
Tissue-Lymph_Node/McCaffrey_TB_MIBI: MIBI
Tissue-Musculoskeletal/Liu_Validation_MIBI: MIBI
Tissue-Nervous/Karimi_Brain_IMC_BrM: IMC
Tissue-Nervous/Karimi_Brain_IMC_Glioma: IMC
Tissue-Nervous/McCaffrey_TB_MIBI: MIBI
Tissue-Pancreas/Keren_PDAC_MIBI: MIBI
Tissue-Renal/Liu_Validation_MIBI: MIBI
Tissue-Reproductive/Liu_Validation_MIBI: MIBI
Tissue-Reproductive/Greenbaum_Maternal-Fetal-Interface_MIBI: MIBI
Tissue-Reproductive/McCaffrey_TB_MIBI: MIBI
Tissue-Skin/Liu_Validation_MIBI: MIBI
Tissue-Skin/Keren_Melanoma_MIBI: MIBI
Tissue-Spleen/Liu_Validation_MIBI: MIBI
Tissue-Thymus/Liu_Validation_MIBI: MIBI
Tissue-Tonsil/Liu_Validation_MIBI: MIBI
Tissue-Tonsil/Nolan_Stellar_CODEX: CODEX
Tissue-GI/Nolan_Stellar_CODEX: CODEX
Tissue-GI/DryadB004_Intestine_CODEX: CODEX
Tissue-GI/DryadB005_Intestine_CODEX: CODEX
Tissue-GI/DryadB006_Intestine_CODEX: CODEX
Tissue-GI/DryadB008_Intestine_CODEX: CODEX
Tissue-GI/DryadRest_Intestine_CODEX: CODEX
Tissue-Spleen/Fan_UF_CODEX: CODEX